version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ness
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && foreman start"
    volumes:
      - .:/myapp
    user: $UID
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
